### ISSUE TITLE
R requirement

### ISSUE THREAD

**Issue by nsheff** [vreuter/SwissR#1]
how are you loading this on Rivanna? I got:
```
#ERROR: this R is version 3.3.0, package 'SwissR' requires R >= 3.4.0
```
(which we don't have). does it really require the cutting edge version?

**Comment by vreuter** [comment]
Probably not, I just specified the latest. I've very likely never tried to load this on Rivanna, just locally.

**Comment by vreuter** [comment]
Fixed with https://github.com/vreuter/SwissR/commit/f0e639157d675a7895c80b31824438b240784588
